run:
	docker-compose -f build/docker-compose.yaml up -d frontend

down:
	docker-compose -f build/docker-compose.yaml down

test:
	docker-compose -f build/docker-compose.yaml exec frontend npm run test
